version: "3.8"
services:
   frontend:
    build: 
    ports:
   backend: 
    build: ./src
    ports:
     -3001:3001
    environment:
      DR_URL: mongodb://db/vidly
   db: 
     image: mongo:4.0-xenial
     ports: 
      -27017:27017
     volumes:
      -vidly:/data/db

volumes:
  vidly:
